apiVersion: apps/v1
kind: Deployment
metadata:
  name: fitnesstracker
spec:
  replicas: 2
  selector:
    matchLabels:
      app: fitnesstracker
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  template:
    metadata:
      labels:
        app: fitnesstracker
    spec:
      containers:
        - name: fitnesstracker
          image: jordanovvvv/fitnesstracker:2023-01-14
          imagePullPolicy: Always
          ports:
            - containerPort: 5000
          resources:
            requests:
              memory: "256Mi"
              cpu: "750m"

