releases:
  - name: fitnesstracker
    chart: fitnesstracker-chart-0.1.0.tgz
    values:
      - replicaCount: 2
        image:
          repository: jordanovvvv/fitnesstracker:2023-01-14
          pullPolicy: Always
        container:
          name: fitnesstracker
          ports:
            - containerPort: 5000
        resources:
          requests:
            memory: "256Mi"
            cpu: "750m"


